task :default => [:sass] do
end

task :sass => [:hello, :fizzy] do
end

task :hello => ['hello.css'] do
  sh 'node-sass hello.scss'
end

task :fizzy => ['fizzy.css'] do
  sh 'node-sass fizzy.scss'
end

task :scss_lint => [] do
  sh 'scss-lint .'
end

task :lint => [:scss_lint] do
end

task :clean => [] do
  begin
    sh 'rm *.css'
  rescue
  end
end
