guard :shell do
  watch(/Rakefile|\..*|(.*\.rb)/) do |m|
    title = 'Lint'
    msg = `rake lint`
    status = ($?.success? && :success) || :failed

    n msg, title, status
    "-> #{msg}"
  end
end
