guard :shell do
  watch("Gemfile") do |m|
    title = "Bundler output"
    msg = "Bundler Failure"
    status = :failed

    if system("bundle")
      msg = "Bundled"
      status = :status
    end

    n msg, title, status

    "-> #{msg}"
  end

  watch(/.+\.hs/) do |m|
    title = "Lint output"
    msg = "Linted"
    status = :failed

    if system("hlint #{m[0]}")
      status = :success
    end

    n msg, title, status

    "-> #{msg}"
  end
end
