source 'http://rubygems.org'

ruby '2.7.1'

gem 'hpricot', '~> 0.8'
gem 'htmlentities', '~> 4.3'
gem 'contracts', '~> 0.4'

group :development do
    gem 'rake', '~> 12.3.3'
    gem 'reek'
    gem 'flay'
    gem 'flog'
    gem 'roodi'
    gem 'cane'
    gem 'excellent'
    gem 'rubocop'
    gem 'tailor'
    gem 'rspec'
    gem 'cucumber'
end
