#!/bin/sh
#
#
# A poor man's NTP proxy, where the clock's wrong and NTP is firewalled.
#
#
# Usage:
#
# $ xdg-open "http://time.is/"
# ...
# Your clock is 4 hours behind.
#
# $ date
# Thu Jul  3 10:18:45 EST 2014
#
# $ ./ntp-http
#
# $ date
# Thu Jul  3 14:18:45 EDT 2014
#
# $ xdg-open "http://time.is/"
# ...
# Your clock is 0.3 seconds behind.

sudo wget -S -O /dev/null google.com 2>&1 | sed -n -e 's/\W*Date: *//p' -eT -eq | xargs -0 sudo date -s
