#!/usr/bin/env sh
#
# Usage:
#
# wget-quickmeme <tag>

DELAY=2 # sec

TAG="$1"

wget -q \
  -mpNHk \
  -D "www.quickmeme.com,s2.quickmeme.com" \
  -w $DELAY \
  -nd \
  -P "$TAG" \
  -I "$TAG/,img/,meme/" \
  -A ".html,.jpg,.jpeg,.gif,.png" \
  "http://www.quickmeme.com/$TAG/"

rm "$TAG/index.html"
