#!/bin/sh
#
# Usage:
#
# wget-tumblr <tumblr-domain>

DELAY=2 # sec

DOMAIN="$1"

wget -q \
  -nd \
  -P "$DOMAIN" \
  -mpNHk \
  -D ".media.tumblr.com,media.tumblr.com,$DOMAIN" \
  -w $DELAY \
  -R "*avatar*,*\?*,*_[0-9][0-9][0-9].*" \
  "http://$DOMAIN"
