source 'http://rubygems.org'

ruby '2.3.0'

group :development do
    gem 'rake'
    gem 'reek'
    gem 'flay'
    gem 'flog'
    gem 'roodi'
    gem 'cane'
    gem 'excellent'
    gem 'rubocop'
    gem 'tailor'
    gem 'rspec'
    gem 'cucumber'
end
