source 'http://rubygems.org'

ruby '2.7.1'

group :development do
    gem 'rake', '~> 12.3.3'
    gem 'reek'
    gem 'flay'
    gem 'flog'
    gem 'roodi'
    gem 'cane'
    gem 'excellent'
    gem 'rubocop'
    gem 'tailor'
    gem 'rspec'
    gem 'cucumber'
end
