#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

# From Adam Jacob Muller's /bin/pidof
# http://www.macosxhints.com/article.php?story=20030618114543169

ps axc |
    awk "{if (\$5==\"$1\") print \$1}"
