#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

curl \
    --socks5 \
    localhost:1080 \
    -u mcandre \
    -s \
    -o /dev/null \
    http://twitter.com/statuses/update.xml \
    -d status="$1"
