source 'http://rubygems.org'

ruby '2.3.0'

gem 'hpricot', '~> 0.8'
gem 'htmlentities', '~> 4.3'
gem 'contracts', '~> 0.4'

group :development do
  gem 'guard'
  gem 'guard-shell', '>= 0.6'
  gem 'rake'
  gem 'reek'
  gem 'flay'
  gem 'flog'
  gem 'roodi'
  gem 'cane'
  gem 'excellent'
  gem 'rubocop'
  gem 'tailor'
  gem 'rspec'
  gem 'cucumber'
end
