#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

# Pending https://github.com/mvdan/sh/issues/511
# v-shfmt &&

v-bashate &&
    v-shlint &&
    v-checkbashisms &&
    v-shellcheck &&
    v-funk &&
    v-slick
