guard :shell do
  watch('Gemfile') do |m|
    title = 'Bundler output'
    msg = 'Bundler Failure'
    status = :failed

    if `bundle`
      msg = 'Bundled'
      status = :status
    end

    n msg, title, status

    "-> #{msg}"
  end

  watch(/.+\.py/) do |m|
    title = 'Lint output'
    msg = 'Linted'
    status = :failed

    msg = `invoke lint`

    if $?.success?
      msg = 'Linted'
      status = :success
    end

    n msg, title, status

    "-> #{msg}"
  end
end
