source 'http://rubygems.org'

ruby '3.0.3'

group :development do
    gem 'rake', '~> 12.3.3'
    gem 'reek', '~> 1.3'
    gem 'flog', '~> 4.3'
    gem 'roodi', '~> 4.0'
    gem 'cane', '~> 2.6'
    gem 'excellent', '~> 2.1'
    gem 'rubocop', '~> 0.49'
    gem 'tailor', '~> 1.4.1'
    gem 'rspec', '~> 3.0'
    gem 'cucumber', '~> 4.0'
end
