guard :shell do
  watch('Gemfile') do |m|
    title = 'Bundler output'
    msg = 'Bundler Failure'
    status = :failed

    if `bundle`
      msg = 'Bundled'
      status = :status
    end

    n msg, title, status

    "-> #{msg}"
  end

  watch(/.+\.php/) do |m|
    title = 'lint output'
    msg = 'Linted'
    status = :failed

    if `make lint`
      status = :success
    end

    n msg, title, status

    "-> #{msg}"
  end
end
