---
name: "Audit"
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"
jobs:
  Audit:
    runs-on: "ubuntu-latest"
    env:
      GOHOME: "/home/runner/go"
    steps:
    - run: "echo \"${PATH}:${GOHOME}/bin\" >> $GITHUB_PATH"
    - uses: "actions/checkout@v4"
    - run: "sudo apt-add-repository ppa:longsleep/golang-backports"
    - run: "sudo apt-get update"
    - run: "sudo apt-get install -y cargo golang-1.21 make"
    - run: "make -f install.mk"
    - run: "make audit"
