---
name: "Lint"
on:
  push:
  pull_request:
jobs:
  Audit:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout"
    - run: "apt-get install -y golang rust"
    - run: "make -f install.mk"
    - run: "make lint"
