---
name: "Lint"
on:
  push:
  pull_request:
jobs:
  Lint:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - run: "sudo apt-add-repository ppa:longsleep/golang-backports"
    - run: "sudo apt-get update"
    - run: "sudo apt-get install -y cargo golang-1.21 make"
    - run: "make -f install.mk"
    - run: "make lint"
